name: dart_utils
description: A Dart utils package.
version: 1.0.0
repository: https://github.com/warrenrhodes/dart_utils
issue_tracker: https://github.com/warrenrhodes/dart_utils/issues

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

